/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class fuck_JniExample */

#ifndef _Included_fuck_JniExample
#define _Included_fuck_JniExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fuck_JniExample
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fuck_JniExample_getStringFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
